#!/bin/bash

set -e

# Mark Duplicates
input_file_MD="/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped.bam"

# Test existence vstupního souboru
if test -e "$input_file_MD"; then
    # Spuštění GATK MarkDuplicates
    java -jar gatk-package-4.2.3.0-local.jar MarkDuplicates \
        -I "$input_file_MD" \
        -O "/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped_MD.bam" \
        -M "/home/user/project/results/test/bam/marked_dup_metrics.txt"
else
    # Výpis chybové zprávy
    echo "Error: Input file for MarkDuplicates does not exist."
    # Ukončení skriptu s chybovým kódem
    exit 1
fi

# Recalibrate Base qualityScores

# Base Recalibrator
input_file_BR="/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped_MD.bam"

# Test existence vstupního souboru
if test -e "$input_file_BR"; then
    # Spuštění Base Recalibrator
    java -jar gatk-package-4.2.3.0-local.jar BaseRecalibrator \
       -I "$input_file_BR" \
       -R "/home/user/project/ref/seq/Homo_sapiens_assembly38.fasta" \
       --known-sites "/home/user/project/ref/annot/1000G_phase1.snps.high_confidence.hg38.vcf.gz" \
       -O "/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped_recal_data.table"
else
    echo "Error: Input file for Base Recalibrator does not exist."
    exit 1
fi

# ApplyBQSR

input_file_AB="/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped_MD.bam"
input_recal_file="/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped_recal_data.table"

# Test existence vstupních souborů
if test -e "$input_file_AB" && test -e "$input_recal_file"; then
    # Spuštění ApplyBQSR
    java -jar gatk-package-4.2.3.0-local.jar ApplyBQSR \
       -R "/home/user/project/ref/seq/Homo_sapiens_assembly38.fasta" \
       -I "$input_file_AB" \
       --bqsr-recal-file "$input_recal_file" \
       -O "/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped_recal.bam"
else
    echo "Error: One or both input files do not exist."
    exit 1
fi

# HaplotypeCaller
input_ref="/home/user/project/ref/seq/Homo_sapiens_assembly38.fasta"
input_recal_bam="/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped_recal.bam"

# Test existence vstupních souborů
if test -e "$input_ref" && test -e "$input_recal_bam"; then
    # Spuštění HaplotypeCaller
    java -Xmx4g -jar gatk-package-4.2.3.0-local.jar HaplotypeCaller \
        -R "$input_ref" \
        -I "$input_recal_bam" \
        -O "/home/user/project/results/test/bam/HG002_HiSeq_sorted_mapped_haplCall.g.vcf.gz" \
        -ERC GVCF
else
    echo "Error: One or both input files do not exist."
    exit 1
fi
